name: Chaining jobs

on:
    workflow_dispatch:
        inputs:
            run-job-3:
                description: "Run job 3"
                default: true
                required: true
                type: boolean
jobs:
    job-1:
        name: Job 1
        runs-on: ubuntu-latest
        steps:
            - name: Output job 1
              run: |
                echo "Hello from Job 1, input for job 3 is : ${{ github.event.input.run-job-3 }} "

    job-2:
        name: Job 2
        runs-on: ubuntu-latest
        needs:
          - job-1
        steps:
            - name: Output Job 2
              run: echo "Hello from Job2"

    job-3:
        name: Job 3
        if: github.event.inputs.run-job-3 == 'true'
        runs-on: ubuntu-latest
        needs:
            - job-2
        steps:
            - name: Output from Job 3
              run: echo "Hello from Job 3"

    job-4:
        name: Job 4
        runs-on: ubuntu-latest
        needs:
            - job-2
            - job-3
        steps:
            - name: Output from Job 4
              run: echo "Hello from job 4"
