name: Variables and contexts

on:
    workflow_dispatch:
        inputs:
            name:
                description: "Person to greet"
                default: "World"
                required: true
env:
    VAR1: myworkflowvar1
    VAR2: myworkflowvar2
    VAR3: myworkflowvar3
jobs:
    job-1:
        name: Job 1
        runs-on: ubuntu-latest
        steps:
            - name: Dump GH context
              env:
                GH_CONTEXT: ${{ toJson(github) }}
              run: echo $GH_CONTEXT | jq "."

    job-2:
        runs-on: ubuntu-latest
        outputs:
            output1: ${{ steps.step1.outputs.step1value }}
        steps:
            - name: Step1
              id: step1
              run: echo "step1value=hello" >> $GITHUB_OUTPUT
    job-3:
        runs-on: ubuntu-latest
        needs: job-2
        env:
            VAR2: "jobmyvar"
        steps:
            - name: Step1 Job3
              env:
                VAR3: "stepvar"
              run: |
                echo ${{ needs.job-2.outputs.output1 }}
                echo $VAR2
                echo $VAR3

